name: Download compiler-rt builtins source
on: [push, workflow_dispatch]
jobs:
  install-headers:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install subversion -y

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Git config
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Remove old source
        run: rm -rf builtins

      - name: Download compiler-rt builtins source
        run: |
          git clone -n --depth=1 --filter=tree:0 https://github.com/llvm/llvm-project
          git -C llvm-project sparse-checkout set --no-cone compiler-rt
          git -C llvm-project checkout
          mv llvm-project/compiler-rt/lib/builtins .

      - name: Push
        run: |
          git config user.name 'ilobilo'
          git config user.email 'ilobilo@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ilobilo/compiler-rt-builtins
          git fetch --all
          git add builtins
          git commit -m "Upload builtins [ci skip]"
          git push origin master
